run:
  timeout: 5m
  issues-exit-code: 1
  tests: true


linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive  # replaced golint
    - misspell
    - goconst

linters-settings:
  revive:
    min-confidence: 0

  misspell:
    locale: US

  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-files:
    - ".*_test.go"
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true